# 作者：胡建星（Jianxing Hu）
# 邮箱：j.hu@pku.edu.cn
# 文件：pyproject.toml
# 说明：构建系统配置
[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "hdl/_version.py"
local_scheme = "no-local-version"
tag_regex = "^(\\d+\\.\\d+\\.\\d+)$"
