[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "hdl/_version.py"
local_scheme = "no-local-version"
tag_regex = "^(\\d+\\.\\d+\\.\\d+)$"
